name: lab 01 valida archivo
run-name: Executed by @${{ github.actor }} Event ${{ github.event_name }} in branch ${{ github.path }}

on:
    push:
        branches: [ master, 'dev-*' ]
        
    pull_request:
        branches: [ master ]
    workflow_dispatch: 
jobs:
    verificacion: # the name of jobs
        runs-on: ubuntu-latest # runners

        steps:
            - name: Download the code
              uses: actions/checkout@v4
            
            - name: Context informtion
              run: |
                echo "--- INFO FROM EVENT ---"
                echo "User: ${{ github.actor }}"
                echo "Event: ${{ github.event_name }}"
                echo "Curret branch: ${{ github.ref }}"
                echo "Repository: ${{ github.repository }}"

  
            - name: checking if the file exist
              run: |
                if [ -f "modo-dia.txt" ]; then
                    echo "✅ El archivo modo-dia.txt existe."
                else 
                    echo "❌ ERROR: Falta el archivo crítico modo-dia.txt"
                    exit 1; # <--- para que el acction sepongo rojo
                fi
            - name: Finish
              run: echo "the acction was succesfull"